# GET http://127.0.0.1:8000/api/v1/products HTTP/1.1

# GET http://127.0.0.1:8000/api/v1/product/1 HTTP/1.1

PUT http://127.0.0.1:8000/api/v1/product/create HTTP/1.1
Content-Type: application/json

{
    "name": "Eugenie",
    "surname": "Bouchard",
    "price": 300
}