version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: python:3

    steps:
      - checkout
      - run:
          command: |
            pipenv install
          name: Testing it

workflows:
  main:
    jobs:
      - build-and-test
