version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-project:
    docker:
      - image: cimg/python:3.10.0

    steps:
      - checkout
      - python/install-packages:
          args: pipenv
          pkg-manager: pip
      - run:
          command: |
            pipenv install --system --deploy
          name: Building the project

workflows:
  main:
    jobs:
      - build-project
