# Generated by Django 3.1.1 on 2020-09-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200904_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedUser',
        ),
    ]
