# Generated by Django 3.1.1 on 2020-11-26 22:21

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_subscribeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.new_directory_path),
        ),
    ]
