# Generated by Django 3.0 on 2020-02-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='user',
            field=models.CharField(default='User', max_length=56),
        ),
    ]
