# Generated by Django 3.1.1 on 2020-10-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='allow_accounts',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='allow_coupons',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='automatic_archive',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='customer_care_email',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='facebook_pixels',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='google_ads',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='google_analytics',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='google_optimize',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='google_tag_manager',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='legal_name',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='mailchimp',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='store_currency',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='dashboardsetting',
            name='telephone',
        ),
    ]
